terminate called after throwing an instance of 'std::runtime_error'
  what():  Please input dot file name